import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { useRouter } from 'next/router'

import styles from '../../styles/DetailMeal.module.css'

export default function MealDetail(props) {
    const router = useRouter();
    const meal = props.meal.meals;
    const category = router.query.category;
    console.log(meal);
    return (
        <div>
            <Head>
                <title>Search result for {meal[0].strMeal}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {
                meal &&
                meal.map(detail => {
                    let url = new URL(`${detail.strYoutube}`);
                    let code = url.search.replace('?v=', '');
                    let embed = `https://www.youtube.com/embed/${code}`;
                    return(
                        <div key={detail.idMeal}>
                            <div className={styles.mealDetail}>
                                <h2 className={styles.mealTitle}>{detail.strMeal}</h2>
                                <Image priority layout={'fixed'} width={300} height={200} src={detail.strMealThumb} alt={detail.strMeal} />
                                <p className={styles.instructions}>{detail.strInstructions}</p>
                                <iframe width="560" height="315" src={embed} title={detail.strMeal} frameBorder="1" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
                            </div>
                            <Link href={`/${category}`}><a className={styles.link}>Back to Home</a></Link>
                        </div>
                    )
                })
                || 'Not Found...'
            }
        </div>
    )
}

export async function getServerSideProps(context) {
    const res = await fetch(`https://www.themealdb.com/api/json/v1/1/lookup.php?i=${context.params.idMeal}`)
    const data = await res.json()
  
    if (!data) {
      return {
        notFound: true,
      }
    }
  
    return {
      props: {
          meal: data,
      }
    }
  }
