import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'

import styles from '../../styles/Category.module.css'

export default function CategoryList(props) {
    const router = useRouter();
    const meals = props.meals.meals;
    const { category } = router.query
    console.log(category);
    return (
        <div>
            <Head>
                <title>Category {category}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.titleMenu}>
                <h2>Here's Menu Based on {category}</h2>
                <Link href="/"><a className={styles.link}>Back to Home</a></Link>
            </div>
            <div className={styles.categoryMenu}>
            {
                meals &&
                meals.map(meal => {
                    return(
                        
                            <div key={meal.idMeal} className={styles.categoryList}>
                                <Link href={`/${category}/${meal.idMeal}`}><a className={styles.marginBottom1}>{meal.strMeal}</a></Link>
                                <Image layout={'fixed'} className={styles.img} width={160} height={120} src={meal.strMealThumb} alt={meal.strMeal} />
                            </div>
                    )
                })
                || 'Loading...'
            }
            </div>
        </div>
    )
}

export async function getServerSideProps(context) {
  const res = await fetch(`https://www.themealdb.com/api/json/v1/1/filter.php?c=${context.params.category}`)
  const data = await res.json()

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: {
        meals: data,
    }
  }
}
