import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home(props) {
  const categories = props.categories.categories;
  // console.log(props.categories);
  return (
    <div className={styles.container}>
      <Head>
        <title>Food List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.titleMenu}>
        <h1 className={styles.hero}>Welcome</h1>
        <h2 className={styles.subHero}>List of all menu</h2>
      </div>
      <div className={styles.categoryMenu}>
      { 
        categories &&
        categories.map(category => {
          return (
            <Link key={category.idCategory} href={`/${category.strCategory}`} passHref={true}>
            <div className={styles.categoryList}>
              <a>{category.strCategory}</a>
            </div>
            </Link>
          )
        })
        || 'Loading...'
      }
      </div>
    </div>
  )
}

export async function getServerSideProps(Context) {
  const res = await fetch("https://www.themealdb.com/api/json/v1/1/categories.php");
  const data = await res.json();
  if(!data) {
    return {
      notFound: true
    }
  }
  return {
    props: {
      categories: data
    }
  }
}
